### ISSUE TITLE
Seeder Data

### ISSUE THREAD

**Issue by vjolaj** [vjolaj/Flask-React-Project#6]
Restaurants 1-3: have 10 reviews
Need at least 10 users.
Other restaurants: 3-5 reviews.
Add a few more menu  items for restaurants 1-3.
Past Orders: 3 past orders for Demo User

**Comment by GenesisM8** [comment]
New users, menu items for the first 6 restaurants and reviews are in. I added a "Show more" button to hide some reviews if the list was too long.

I couldn't add any data for Past Orders because it kept showing 0 items. Even after trying to seed items separately in the "orderitems" table, the issue remained (I left the file with the code commented out in case somebody wants to try, just needs to be invoked in the __init__.py).  However, in case there are no Past Orders, I have included a message: "You haven't placed any orders yet. Click here to start shopping." This will redirect users to "/restaurants"
